# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/sf_COSC363/Labs/Assignment 1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/sf_COSC363/Labs/Assignment 1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sf_COSC363/Labs/Assignment 1/CMakeFiles" "/media/sf_COSC363/Labs/Assignment 1/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/sf_COSC363/Labs/Assignment 1/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main.out

# Build rule for target.
Main.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main.out
.PHONY : Main.out

# fast build rule for target.
Main.out/fast:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/build
.PHONY : Main.out/fast

controller/main.o: controller/main.cpp.o

.PHONY : controller/main.o

# target to build an object file
controller/main.cpp.o:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/controller/main.cpp.o
.PHONY : controller/main.cpp.o

controller/main.i: controller/main.cpp.i

.PHONY : controller/main.i

# target to preprocess a source file
controller/main.cpp.i:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/controller/main.cpp.i
.PHONY : controller/main.cpp.i

controller/main.s: controller/main.cpp.s

.PHONY : controller/main.s

# target to generate assembly for a file
controller/main.cpp.s:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/controller/main.cpp.s
.PHONY : controller/main.cpp.s

model/Cannon/Cannon.o: model/Cannon/Cannon.cpp.o

.PHONY : model/Cannon/Cannon.o

# target to build an object file
model/Cannon/Cannon.cpp.o:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Cannon/Cannon.cpp.o
.PHONY : model/Cannon/Cannon.cpp.o

model/Cannon/Cannon.i: model/Cannon/Cannon.cpp.i

.PHONY : model/Cannon/Cannon.i

# target to preprocess a source file
model/Cannon/Cannon.cpp.i:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Cannon/Cannon.cpp.i
.PHONY : model/Cannon/Cannon.cpp.i

model/Cannon/Cannon.s: model/Cannon/Cannon.cpp.s

.PHONY : model/Cannon/Cannon.s

# target to generate assembly for a file
model/Cannon/Cannon.cpp.s:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Cannon/Cannon.cpp.s
.PHONY : model/Cannon/Cannon.cpp.s

model/Castle/Castle.o: model/Castle/Castle.cpp.o

.PHONY : model/Castle/Castle.o

# target to build an object file
model/Castle/Castle.cpp.o:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Castle/Castle.cpp.o
.PHONY : model/Castle/Castle.cpp.o

model/Castle/Castle.i: model/Castle/Castle.cpp.i

.PHONY : model/Castle/Castle.i

# target to preprocess a source file
model/Castle/Castle.cpp.i:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Castle/Castle.cpp.i
.PHONY : model/Castle/Castle.cpp.i

model/Castle/Castle.s: model/Castle/Castle.cpp.s

.PHONY : model/Castle/Castle.s

# target to generate assembly for a file
model/Castle/Castle.cpp.s:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Castle/Castle.cpp.s
.PHONY : model/Castle/Castle.cpp.s

model/Robots/Robots.o: model/Robots/Robots.cpp.o

.PHONY : model/Robots/Robots.o

# target to build an object file
model/Robots/Robots.cpp.o:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Robots/Robots.cpp.o
.PHONY : model/Robots/Robots.cpp.o

model/Robots/Robots.i: model/Robots/Robots.cpp.i

.PHONY : model/Robots/Robots.i

# target to preprocess a source file
model/Robots/Robots.cpp.i:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Robots/Robots.cpp.i
.PHONY : model/Robots/Robots.cpp.i

model/Robots/Robots.s: model/Robots/Robots.cpp.s

.PHONY : model/Robots/Robots.s

# target to generate assembly for a file
model/Robots/Robots.cpp.s:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Robots/Robots.cpp.s
.PHONY : model/Robots/Robots.cpp.s

model/Shapes/Shapes.o: model/Shapes/Shapes.cpp.o

.PHONY : model/Shapes/Shapes.o

# target to build an object file
model/Shapes/Shapes.cpp.o:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Shapes/Shapes.cpp.o
.PHONY : model/Shapes/Shapes.cpp.o

model/Shapes/Shapes.i: model/Shapes/Shapes.cpp.i

.PHONY : model/Shapes/Shapes.i

# target to preprocess a source file
model/Shapes/Shapes.cpp.i:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Shapes/Shapes.cpp.i
.PHONY : model/Shapes/Shapes.cpp.i

model/Shapes/Shapes.s: model/Shapes/Shapes.cpp.s

.PHONY : model/Shapes/Shapes.s

# target to generate assembly for a file
model/Shapes/Shapes.cpp.s:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/Shapes/Shapes.cpp.s
.PHONY : model/Shapes/Shapes.cpp.s

model/SpaceShip/Spaceship.o: model/SpaceShip/Spaceship.cpp.o

.PHONY : model/SpaceShip/Spaceship.o

# target to build an object file
model/SpaceShip/Spaceship.cpp.o:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/SpaceShip/Spaceship.cpp.o
.PHONY : model/SpaceShip/Spaceship.cpp.o

model/SpaceShip/Spaceship.i: model/SpaceShip/Spaceship.cpp.i

.PHONY : model/SpaceShip/Spaceship.i

# target to preprocess a source file
model/SpaceShip/Spaceship.cpp.i:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/SpaceShip/Spaceship.cpp.i
.PHONY : model/SpaceShip/Spaceship.cpp.i

model/SpaceShip/Spaceship.s: model/SpaceShip/Spaceship.cpp.s

.PHONY : model/SpaceShip/Spaceship.s

# target to generate assembly for a file
model/SpaceShip/Spaceship.cpp.s:
	$(MAKE) -f CMakeFiles/Main.out.dir/build.make CMakeFiles/Main.out.dir/model/SpaceShip/Spaceship.cpp.s
.PHONY : model/SpaceShip/Spaceship.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Main.out"
	@echo "... controller/main.o"
	@echo "... controller/main.i"
	@echo "... controller/main.s"
	@echo "... model/Cannon/Cannon.o"
	@echo "... model/Cannon/Cannon.i"
	@echo "... model/Cannon/Cannon.s"
	@echo "... model/Castle/Castle.o"
	@echo "... model/Castle/Castle.i"
	@echo "... model/Castle/Castle.s"
	@echo "... model/Robots/Robots.o"
	@echo "... model/Robots/Robots.i"
	@echo "... model/Robots/Robots.s"
	@echo "... model/Shapes/Shapes.o"
	@echo "... model/Shapes/Shapes.i"
	@echo "... model/Shapes/Shapes.s"
	@echo "... model/SpaceShip/Spaceship.o"
	@echo "... model/SpaceShip/Spaceship.i"
	@echo "... model/SpaceShip/Spaceship.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

